source 'https://rubygems.org'
gem 'lol_dba'
gem 'thin', '~>1.6.2'
gem 'newrelic_rpm'
# gem 'ruby', '1.9.3p545'
gem 'backbone-on-rails'
gem 'bootstrap-sass'
gem 'font-awesome-rails'
gem 'rails', '4.1.1'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'
gem 'rails_12factor'
gem 'figaro'
gem 'paperclip', '~> 4.1'
gem 'aws-sdk'
gem 'cocaine'

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
end