# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

AWS_DEV_BUCKET: wakebnb-dev
AWS_PROD_BUCKET: wakebnb-production
AWS_ACCESS_KEY_ID: AKIAJ7SAPXL5DZ6KJL2Q
AWS_SECRET_ACCESS_KEY: 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
GOOGLE_MAPS_API: AIzaSyBWgVTz5cd_FfD_51bl2ETbfT6EyEAK47A
NEW_RELIC_KEY: 266b6c54759900a033ceda75c3e6ce3516a4e37b