# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

AWS_DEV_BUCKET: wakebnb-dev
AWS_PROD_BUCKET: wakebnb-production
AWS_ACCESS_KEY_ID: AKIAIISE5ILJJJDIGDGQ
AWS_SECRET_ACCESS_KEY: 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
GOOGLE_MAPS_API: AIzaSyBWgVTz5cd_FfD_51bl2ETbfT6EyEAK47A